name: Benchmark
run-name: Running benchmarking and updating results in README.adoc ðŸš€
on:
  push:
    branches:
      - main

jobs:
  Run-Benchmarking:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run benchmarking
        run: |
          cd ./runner
          cargo build --release --verbose
          cargo run --release --verbose --bin bench-ci
          cd ..
      - name: Generate new README.adoc
        run: |
          cp ./.github/data/README.adoc ./README.adoc
          sed -i "s/include\:\:benchmark\.csv\[\]/$(sed -e 's/[\&/]/\\&/g' -e 's/$/\\n/' ./.github/data/benchmark.csv | tr -d '\n')/" ./README.adoc
      - name: Commit new README.adoc
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.adoc
          git diff-index --quiet HEAD || git commit -m "Updated README.adoc with new benchmark results"
          git push
